/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterPanel: typeof import('./src/components/CharacterPanel.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    SettingsDrawer: typeof import('./src/components/SettingsDrawer.vue')['default']
  }
}
